local M = {
  "nvim-telescope/telescope.nvim",
  commit = "40c31fdde93bcd85aeb3447bb3e2a3208395a868",
  event = "Bufenter",
  cmd = { "Telescope" },
	dependencies = {
    {
      "nvim-lua/plenary.nvim",
      commit = "9a0d3bf7b832818c042aaf30f692b081ddd58bd9",
    }
	}
}

M.opts = {
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    path_display = { "smart" },
    file_ignore_patterns = {
    "repos/",
    ".git/",
    "node_modules",
    "%.iso",
    "%.pdf",
    "%.mkv",
    "%.mp4",
    "%.zip",
    "%.exe",
    "%.dll",
    "%.bin",
    "%.jar",
    "%.png",
    "%.jpg",
    "%.jpeg",
    "%.gif",
    "%.bmp",
    "%.ico",
    "%.psd",
    "%.tiff",
    "%.webp",
    "%.avi",
    "%.mov",
    "%.flv",
    "%.wav",
    "%.mp3",
    "%.ogg",
    "%.flac",
    "%.wma",
    "%.aac",
    "%.dat",
    "%.tar",
    "%.gz",
    "%.bz2",
    "%.7z",
    "%.rar",
    "%.zip",
    "%.dmg",
    "%.pkg",
    "%.ppt",
    "%.pptx",
    "%.doc",
    "%.docx",
    "%.xls",
    "%.xlsx",
    "%.ppt",
    "%.pptx",
    "%.doc",
    "%.docx",
    "%.xls",
    "%.xlsx",
    "%.bin",
    "%.obj",
    "%.class",
    "%.pyc",
    "%.o",
    "%.a",
    "%.lib",
    "%.so",
    "%.dylib",
    "%.dll",
    "%.exe",
    "%.com",
    "%.bat",
    "%.msi",
    "%.app",
    "%.ipa",
    "%.apk",
    "%.elf",
    "%.deb",
    "%.rpm",
    }
  },
}

return M
