vim.o.number = true
vim.o.relativenumber = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.smarttab = true
vim.o.wrap = false
vim.o.clipboard = "unnamedplus"
vim.o.scrolloff = 80
vim.o.virtualedit = "block"
vim.o.hlsearch = false
vim.o.inccommand = "split"
vim.o.ignorecase = true
vim.o.termguicolors = true

vim.g.mapleader = " "
