#!/bin/bash

# Array of my FAV Colorscripts
COLOR=(5 6 16 35 41 50 32)

# Generating a Random number from the Given array
ARG=${COLOR[RANDOM%${#COLOR[@]}]}

# Executing colorscript command used -e flag and ARG variable
colorscript -e $ARG
