#!/bin/bash


if [[ $(cat /sys/class/power_supply/BAT0/capacity) -le 20 ]]
then
    DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus setpriv --euid=1000 notify-send -t 300000 -u critical "Battery is low. Please plug in your power cable." && espeak "Warning: Battery is under 20%."     
fi
