#!/bin/bash


ANS=$(echo -e "Shutdown\nSuspend\nHibernate\nReboot\nLock\nLogout" | dmenu -i -p "Power Menu:" -fn 'monospace-13' )

#echo $ANS

if [ "$ANS" == "Shutdown" ]
then
    systemctl poweroff
elif [ "$ANS" == "Hibernate" ]
then 
    systemctl hibernate
elif [ "$ANS" == "Suspend" ]
then
    betterlockscreen -l & systemctl suspend
elif [ "$ANS" == "Lock" ]
then
    betterlockscreen -l
elif [ "$ANS" == "Reboot" ]
then
    reboot
elif [ "$ANS" == "Logout" ]
then
    i3-msg exit
fi

