#!/bin/bash
NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LP='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

echo -e "${LP}Removed Packages or Installed Packages? (R/I)${NC}"
read ANS

echo -e "${YELLOW}Enter Tail Command Argument: ${NC}"
read ARG

if [ "$ANS" == "R" ]
then 
    less /var/log/pacman.log | grep removed | sed -e 's/\[ALPM\] removed //' -e 's/(.*$//'  | tail -n $ARG
elif [ "$ANS" == "I" ]
then
    less /var/log/pacman.log | grep installed | sed -e 's/\[ALPM\] installed //' -e 's/(.*$//'  | tail -n $ARG
else
    echo -e "${RED}Incorrect Input. Terminating...${NC}"
fi
