#!/bin/bash


ANS=$(echo -e "Shutdown\nSuspend\nReboot\nLock" | dmenu -i -p "Power Menu:" -fn 'monospace-10' )

#echo $ANS

if [ "$ANS" == "Shutdown" ]
then
    systemctl poweroff
elif [ "$ANS" == "Suspend" ]
then
    betterlockscreen -l & systemctl suspend
elif [ "$ANS" == "Lock" ]
then
    betterlockscreen -l
elif [ "$ANS" == "Reboot" ]
then
    reboot
fi

